[package]
name = "rs-seed2body-grpc-server"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"

[dependencies.tokio]
version = "1.40.0"
default-features = false
features = [
	"macros",
	"rt-multi-thread",
]

[dependencies.prost]
version = "0.13.2"
default-features = false
features = [
	"derive",
	"std",
]

[dependencies.tonic]
version = "0.12.2"
default-features = false
features = [
	"codegen",
	"prost",
	"transport",
]

[build-dependencies.tonic-build]
version = "0.12.2"
default-features = false
features = [
	"prost",
	"transport",
]
