[package]
name = "rs-env2page"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [
	"cdylib",
]

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 16

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
unwrap_used = "forbid"
